(copy_files ../*.*)
(alias (name runtest)
  (deps (alias runtest_config)))
; TEST FILE "max.c"
(alias (name "max.wtests")
  (deps (alias "max.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "max.c")
  (deps (alias "max.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/hol4/max.c
  (alias "max.0.exec.wtests")
  (targets "max.0.err.log" "max.0.res.log"  )
  (deps "max.0.exec.wtests" "../oracle/max.0.res.oracle" "../oracle/max.0.err.oracle"  "max.c"  (package frama-c)  (package "frama-c-arm8") )
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (run frama-c-wtests -brief "max.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=arm8    max.c -arm8 -arm8-type hol > \"max.0.res.log\" 2> \"max.0.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "max.c"
  (alias "max.0.exec")
  (deps  "max.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=arm8    max.c -arm8 -arm8-type hol")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "max.c"
  (alias "max.0.exec.show")
  (deps  "max.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=arm8    max.c -arm8 -arm8-type hol > \"max.0.res.log\" 2> \"max.0.err.log\"'"))
)
(rule
  (alias "max.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/max.0.res.oracle" "max.0.res.log"))
)
(rule
  (alias "max.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/max.0.err.oracle" "max.0.err.log"))
)
(alias (name "max.diff")
  (deps (alias "max.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
(alias (name "runtest_config")
  (deps (alias "max.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
; TEST FILE "swap.c"
(alias (name "swap.wtests")
  (deps (alias "swap.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "swap.c")
  (deps (alias "swap.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/hol4/swap.c
  (alias "swap.0.exec.wtests")
  (targets "swap.0.err.log" "swap.0.res.log"  )
  (deps "swap.0.exec.wtests" "../oracle/swap.0.res.oracle" "../oracle/swap.0.err.oracle"  "swap.c"  (package frama-c)  (package "frama-c-arm8") )
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (run frama-c-wtests -brief "swap.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=arm8    swap.c -arm8 -arm8-type hol > \"swap.0.res.log\" 2> \"swap.0.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "swap.c"
  (alias "swap.0.exec")
  (deps  "swap.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=arm8    swap.c -arm8 -arm8-type hol")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "swap.c"
  (alias "swap.0.exec.show")
  (deps  "swap.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=arm8    swap.c -arm8 -arm8-type hol > \"swap.0.res.log\" 2> \"swap.0.err.log\"'"))
)
(rule
  (alias "swap.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/swap.0.res.oracle" "swap.0.res.log"))
)
(rule
  (alias "swap.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/swap.0.err.oracle" "swap.0.err.log"))
)
(alias (name "swap.diff")
  (deps (alias "swap.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
(alias (name "runtest_config")
  (deps (alias "swap.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
; TEST FILE "update_sat.c"
(alias (name "update_sat.wtests")
  (deps (alias "update_sat.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "update_sat.c")
  (deps (alias "update_sat.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/hol4/update_sat.c
  (alias "update_sat.0.exec.wtests")
  (targets "update_sat.0.err.log" "update_sat.0.res.log"  )
  (deps "update_sat.0.exec.wtests" "../oracle/update_sat.0.res.oracle" "../oracle/update_sat.0.err.oracle"  "update_sat.c"  (package frama-c)  (package "frama-c-arm8") )
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (run frama-c-wtests -brief "update_sat.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=arm8    update_sat.c -arm8 -arm8-type hol > \"update_sat.0.res.log\" 2> \"update_sat.0.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "update_sat.c"
  (alias "update_sat.0.exec")
  (deps  "update_sat.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=arm8    update_sat.c -arm8 -arm8-type hol")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "update_sat.c"
  (alias "update_sat.0.exec.show")
  (deps  "update_sat.c"  (package frama-c)  (package "frama-c-arm8")  (universe))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=arm8    update_sat.c -arm8 -arm8-type hol > \"update_sat.0.res.log\" 2> \"update_sat.0.err.log\"'"))
)
(rule
  (alias "update_sat.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/update_sat.0.res.oracle" "update_sat.0.res.log"))
)
(rule
  (alias "update_sat.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
(action (diff "../oracle/update_sat.0.err.oracle" "update_sat.0.err.log"))
)
(alias (name "update_sat.diff")
  (deps (alias "update_sat.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
(alias (name "runtest_config")
  (deps (alias "update_sat.diff"))
  (enabled_if (and true %{lib-available:frama-c-arm8.core}))
)
(alias (name disabled_runtest)
  (deps (alias disabled_runtest_config)))
(alias (name runtest)
  (deps (alias disabled_runtest)))
(alias (name runtest_config)
  (deps (alias disabled_runtest_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_runtest_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-arm8.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/hol4/runtest_config\n")
                 (echo "- \%{lib-available:frama-c-arm8.core}: " %{lib-available:frama-c-arm8.core} "\n")
  ))
)

