(rule (target "max.0.err.oracle") (mode fallback) (action (write-file "max.0.err.oracle" "")))
(rule (target "max.0.res.oracle") (mode fallback) (action (write-file "max.0.res.oracle" "")))
(rule (target "swap.0.err.oracle") (mode fallback) (action (write-file "swap.0.err.oracle" "")))
(rule (target "swap.0.res.oracle") (mode fallback) (action (write-file "swap.0.res.oracle" "")))
(rule (target "update_sat.0.err.oracle") (mode fallback) (action (write-file "update_sat.0.err.oracle" "")))
(rule (target "update_sat.0.res.oracle") (mode fallback) (action (write-file "update_sat.0.res.oracle" "")))

